--- 
javascripts: 
- base: 
  - jquery-1.3.2.min
  - jmodal
  - jquery.validate.min
  - jquery.tooltip.min
  - jquery.form
  - swfobject
  - application
stylesheets: 
- base: 
  - application
  - jmodal
